# Generated by Django 5.2.16 on 2026-08-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='next_item_number',
            field=models.IntegerField(default=1),
        ),
    ]
