# Generated by Django 5.2.16 on 2026-08-14 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_rename_card_to_workitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='item_type',
            field=models.CharField(choices=[('epic', 'Epic'), ('story', 'Story'), ('task', 'Task'), ('bug', 'Bug'), ('subtask', 'Subtask')], default='task', max_length=10),
        ),
        migrations.AddField(
            model_name='workitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='boards.workitem'),
        ),
    ]
