# Generated by Django 5.2.16 on 2026-08-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_workitem_item_type_and_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='key',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
