# Generated by Django 5.2.16 on 2026-08-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0010_backfill_work_item_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workitem',
            name='key',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
