# Generated by Django 5.2.16 on 2026-08-14 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0012_component'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkItemLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_item_links_created', to=settings.AUTH_USER_MODEL)),
                ('item_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_as_a', to='boards.workitem')),
                ('item_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_as_b', to='boards.workitem')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('item_a', 'item_b'), name='unique_work_item_link')],
            },
        ),
    ]
