# Generated by Django 5.2.16 on 2026-08-18 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0015_screen_and_screen_field'),
        ('projects', '0002_project_next_item_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectScreenAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('epic', 'Epic'), ('story', 'Story'), ('task', 'Task'), ('bug', 'Bug'), ('subtask', 'Subtask')], max_length=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_assignments', to='projects.project')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='boards.screen')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('project', 'item_type'), name='unique_screen_assignment_per_item_type')],
            },
        ),
    ]
