# Generated by Django 5.2.16 on 2026-08-18 08:12
#
# Hand-edited after generation: MySQL/InnoDB refuses a UNIQUE key over a
# TEXT/BLOB column with no explicit prefix length ("BLOB/TEXT column
# 'value' used in key specification without a key length", error 1170).
# The model keeps `value = models.TextField()` with an unprefixed
# UniqueConstraint (see boards/models.py) so Django's model state — and
# `makemigrations`' idea of what's already applied — matches the brief
# exactly. Only the actual DDL sent to MySQL differs: the constraint is
# created via RunSQL with an explicit value(255) prefix instead of the
# CreateModel operation's inline constraint. 255 utf8mb4 characters is
# 1020 bytes, comfortably under InnoDB's 3072-byte max index prefix, and
# every value this table actually stores (numbers, dates, option/user ids,
# short text up to its own 255-char validation limit) fits inside it
# untruncated; only a text_long value could in principle exceed 255
# characters, in which case uniqueness is enforced on its first 255
# characters rather than the full value — an acceptable tradeoff since the
# constraint's job is duplicate-row hygiene, not business validation.
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0016_project_screen_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkItemFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='boards.customfield')),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='boards.workitem')),
            ],
        ),
        migrations.RunSQL(
            sql=(
                "ALTER TABLE boards_workitemfieldvalue "
                "ADD CONSTRAINT unique_work_item_field_value "
                "UNIQUE (work_item_id, field_id, value(255))"
            ),
            reverse_sql=(
                "ALTER TABLE boards_workitemfieldvalue "
                "DROP INDEX unique_work_item_field_value"
            ),
            state_operations=[
                migrations.AddConstraint(
                    model_name='workitemfieldvalue',
                    constraint=models.UniqueConstraint(
                        fields=('work_item', 'field', 'value'),
                        name='unique_work_item_field_value',
                    ),
                ),
            ],
        ),
    ]
